import json

es_updates = {
  "QuoteModal": {
    "start_quote": "Iniciar Cotización",
    "step_x_of_7": "Paso {step} de 7",
    "step1_title": "Origen del Código",
    "step1_new": "Proyecto Nuevo",
    "step1_new_desc": "Empezamos con una hoja en blanco, desde cero.",
    "step1_legacy": "Proyecto Existente",
    "step1_legacy_desc": "Hay que revisar, rescatar o mejorar código que ya tienes.",
    "step2_title": "Tamaño de la Empresa",
    "step2_startup": "Emprendimiento",
    "step2_startup_desc": "1 a 10 personas. Enfoque en validar rápido el MVP.",
    "step2_sme": "PYME",
    "step2_sme_desc": "11 a 50 personas. Procesos establecidos y bases sólidas.",
    "step2_enterprise": "Corporativo",
    "step2_enterprise_desc": "50+ personas. Alta disponibilidad, SLAs y compliance.",
    "step3_title": "¿Qué tipo de proyecto necesitas?",
    "step3_subtitle": "Puedes seleccionar múltiples opciones:",
    "step3_app": "App Móvil",
    "step3_app_desc": "Desarrollo Nativo o Multiplataforma.",
    "step3_web": "Sitio Web",
    "step3_web_desc": "Plataformas Web y E-commerce.",
    "step3_cloud": "Cloud",
    "step3_cloud_desc": "Arquitectura e infraestructura Cloud.",
    "step4_title": "Complejidad Técnica",
    "step4_basic": "Básica",
    "step4_basic_desc": "Informativo, formularios simples, sin cuentas de usuario.",
    "step4_intermediate": "Intermedia",
    "step4_intermediate_desc": "Perfiles de usuario, panel de administración y pagos.",
    "step4_advanced": "Avanzada",
    "step4_advanced_desc": "Operaciones en tiempo real, miles de usuarios o logística compleja.",
    "step5_title": "Estado del Diseño UX/UI",
    "step5_ready": "Diseño Listo",
    "step5_ready_desc": "Tienen flujos y pantallas definidas en Figma.",
    "step5_scratch": "Desde Cero",
    "step5_scratch_desc": "LogikaMobile debe diseñarlo desde cero.",
    "step6_title": "Integraciones Externas",
    "step6_isolated": "Sistema Aislado",
    "step6_isolated_desc": "Operará de manera independiente sin conectarse a otros sistemas.",
    "step6_critical": "Integraciones Externas",
    "step6_critical_desc": "Requiere conectar con sistemas de tu empresa, bancos o hardware.",
    "step7_title": "La Urgencia (Triángulo de Hierro)",
    "step7_normal": "Normal",
    "step7_normal_desc": "Tiempos estándar de desarrollo.",
    "step7_fast": "Rápida",
    "step7_fast_desc": "Necesitamos meter el acelerador.",
    "step7_urgent": "Urgente",
    "step7_urgent_desc": "Prioridad máxima. Lo necesitas para ayer.",
    "back": "Atrás",
    "continue": "Continuar",
    "quote_btn": "Cotizar",
    "result_title": "Estimado de Inversión",
    "result_currency": "USD",
    "result_desc": "Ten en cuenta que esta es una estimación rápida. Como aún no conocemos los detalles exactos de tu operación, el precio final podría variar. Cuéntanos tu visión y armaremos una propuesta a tu medida.",
    "contact_team": "Contactar Equipo",
    "close": "Cerrar",
    "contact_title": "Hagámoslo realidad",
    "contact_desc": "Déjanos tus datos. Generaremos un correo con los detalles técnicos de tu cotización listo para ser enviado.",
    "form_name": "Nombre",
    "form_name_ph": "Ej. Ana Pérez",
    "form_email": "Correo Electrónico",
    "form_email_ph": "ana@empresa.com",
    "form_email_err": "Por favor ingresa un correo válido.",
    "form_phone": "Teléfono",
    "form_pref": "Medio de Contacto Preferido",
    "form_pref_opt_default": "Selecciona una opción",
    "form_pref_opt_whatsapp": "WhatsApp",
    "form_pref_opt_email": "Correo Electrónico",
    "form_pref_opt_call": "Llamada Telefónica",
    "form_desc": "Breve Descripción del Proyecto",
    "form_desc_ph": "Cuéntanos un poco de tu idea, objetivos o requerimientos principales...",
    "btn_sending": "Enviando...",
    "btn_send": "Enviar Solicitud",
    "err_send": "Hubo un error al enviar la solicitud. Intenta de nuevo.",
    "err_conn": "Hubo un error de conexión al enviar la solicitud.",
    "success_title": "¡Solicitud Enviada!",
    "success_desc": "Hemos recibido tu información y la estimación técnica de tu proyecto de manera exitosa. Nuestro equipo estratégico la revisará y te contactaremos en breve a tu correo.",
    "understood": "Entendido"
  }
}

en_updates = {
  "QuoteModal": {
    "start_quote": "Start Quote",
    "step_x_of_7": "Step {step} of 7",
    "step1_title": "Code Origin",
    "step1_new": "New Project",
    "step1_new_desc": "We start with a blank page, from scratch.",
    "step1_legacy": "Existing Project",
    "step1_legacy_desc": "We need to review, rescue or improve code you already have.",
    "step2_title": "Company Size",
    "step2_startup": "Startup",
    "step2_startup_desc": "1 to 10 people. Focus on validating the MVP quickly.",
    "step2_sme": "SME",
    "step2_sme_desc": "11 to 50 people. Established processes and solid foundations.",
    "step2_enterprise": "Enterprise",
    "step2_enterprise_desc": "50+ people. High availability, SLAs and compliance.",
    "step3_title": "What kind of project do you need?",
    "step3_subtitle": "You can select multiple options:",
    "step3_app": "Mobile App",
    "step3_app_desc": "Native or Cross-platform development.",
    "step3_web": "Website",
    "step3_web_desc": "Web Platforms and E-commerce.",
    "step3_cloud": "Cloud",
    "step3_cloud_desc": "Cloud Architecture and infrastructure.",
    "step4_title": "Technical Complexity",
    "step4_basic": "Basic",
    "step4_basic_desc": "Informative, simple forms, no user accounts.",
    "step4_intermediate": "Intermediate",
    "step4_intermediate_desc": "User profiles, admin panel, and payments.",
    "step4_advanced": "Advanced",
    "step4_advanced_desc": "Real-time operations, thousands of users, or complex logistics.",
    "step5_title": "UX/UI Design Status",
    "step5_ready": "Design Ready",
    "step5_ready_desc": "You have flows and screens defined in Figma.",
    "step5_scratch": "From Scratch",
    "step5_scratch_desc": "LogikaMobile needs to design it from scratch.",
    "step6_title": "External Integrations",
    "step6_isolated": "Isolated System",
    "step6_isolated_desc": "Will operate independently without connecting to other systems.",
    "step6_critical": "External Integrations",
    "step6_critical_desc": "Requires connecting with your company's systems, banks, or hardware.",
    "step7_title": "Urgency (Iron Triangle)",
    "step7_normal": "Normal",
    "step7_normal_desc": "Standard development times.",
    "step7_fast": "Fast",
    "step7_fast_desc": "We need to step on the gas.",
    "step7_urgent": "Urgent",
    "step7_urgent_desc": "Highest priority. You needed it yesterday.",
    "back": "Back",
    "continue": "Continue",
    "quote_btn": "Quote",
    "result_title": "Investment Estimate",
    "result_currency": "USD",
    "result_desc": "Keep in mind that this is a quick estimate. Since we don't know the exact details of your operation yet, the final price could vary. Tell us your vision and we will build a tailored proposal.",
    "contact_team": "Contact Team",
    "close": "Close",
    "contact_title": "Let's make it happen",
    "contact_desc": "Leave us your details. We will generate an email with the technical details of your quote ready to be sent.",
    "form_name": "Name",
    "form_name_ph": "E.g. Jane Doe",
    "form_email": "Email",
    "form_email_ph": "jane@company.com",
    "form_email_err": "Please enter a valid email.",
    "form_phone": "Phone",
    "form_pref": "Preferred Contact Method",
    "form_pref_opt_default": "Select an option",
    "form_pref_opt_whatsapp": "WhatsApp",
    "form_pref_opt_email": "Email",
    "form_pref_opt_call": "Phone Call",
    "form_desc": "Brief Project Description",
    "form_desc_ph": "Tell us a bit about your idea, goals, or main requirements...",
    "btn_sending": "Sending...",
    "btn_send": "Send Request",
    "err_send": "There was an error sending the request. Try again.",
    "err_conn": "There was a connection error when sending the request.",
    "success_title": "Request Sent!",
    "success_desc": "We have successfully received your information and the technical estimate for your project. Our strategic team will review it and contact you shortly.",
    "understood": "Understood"
  }
}

def update_file(filepath, updates):
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    data.update(updates)
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

update_file('messages/es.json', es_updates)
update_file('messages/en.json', en_updates)
print("Updated JSON files for QuoteModal")
